name: dsit_thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.3.1
  - pandas>=2.1.3
  - numpy>=1.26.2
  - networkx>=3.2.1
  - seaborn>=0.13.0
  - jupyterlab>=4.0.8
  - langchain>=0.1
  - pyvis>=0.3.1
  - tqdm>=4.38
  - yachalk>=0.1.5
  - pyarrow>=15.0.2
  - matplotlib
  # WikiGraphs START #
  - absl-py==0.10.0
  - dm-haiku
  - jax>=0.2.13
  - jraph
  - nltk>=3.6.2
  - optax>=0.0.6
  - scikit-learn>=0.24.2
  # WikiGraphs END #
  # CCDS START #
  # Added due to adopting Cookiecutter Data Science V2 template
  - black
  - flake8
  - isort
  - typer
  - loguru
  - python-dotenv
  - mkdocs
  - mkdocstrings
  # CCDS END #
  - pip:
    - ollama>=0.1.7
    - rdflib
    - rdfpandas
    # - -e .
