name: llmgrapher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.3.1
  - pandas>=2.1.3
  - numpy>=1.26.2
  - networkx>=3.2.1
  - seaborn>=0.13.0
  - jupyterlab>=4.0.8
  - langchain>=0.0.335
  - pypdf>=3.17.0
  - pyvis>=0.3.1
  - tqdm>=4.38
  - yachalk>=0.1.5
  - pyarrow>=15.0.2
  - pip:
    - unstructured>=0.10.30
    # Uncomment below line and comment the above to include all supported documents in the unstructured library
    # - unstructured[all-docs]>=0.10.30
    - ollama>=0.1.7
